services:
  - type: web
    name: merchantpro-op-app-integration
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python merchantpro_json_feed.py"
